server:
    port: 10020
    enable-csrf: true
    tomcat:
       uriEncoding: UTF-8

---
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: @jdbc.url@
        username: @jdbc.user@
        password: @jdbc.password@